name: Fast Element benchmark jobs

on: [pull_request]

jobs:
    setup:
      name: Setup Tachometer Reporting
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: nelonoel/branch-name@v1.0.1
        - run: echo ${BRANCH_NAME}

    update10th:
      name: Run update 10th element benchmark
      needs: [setup]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v1
          with:
              node-version: "16.x"
        - name: Run tachometer and generate results file
          run: |
              cd packages/utilities/fast-benchmarks
              yarn install
              yarn run benchmark:fast-element:test
        # Upload this benchmarks results
        - name: Upload results
          uses: actions/upload-artifact@v2
          with:
              name: results
              path: packages/utilities/fast-benchmarks/results/fast-element_test-update10th.json
    render:
      name: Run create 10k element benchmark
      needs: [setup]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v1
          with:
              node-version: "16.x"
        - name: Get local branch name
          uses: nelonoel/branch-name@v1.0.1

        - name: Run tachometer and generate results file
          run: |
              cd packages/utilities/fast-benchmarks
              yarn install
              yarn run benchmark --library=fast-element --benchmark=render --versions local latest --localBenchFile=index2 --branchName=${BRANCH_NAME}
        # Upload this benchmarks results
        - name: Upload results
          uses: actions/upload-artifact@v2
          with:
              name: results
              path: |
                  packages/utilities/fast-benchmarks/results/fast-element_render-update10th.json
                  packages/utilities/fast-benchmarks/results/fast-element_render-create10k.json
                  packages/utilities/fast-benchmarks/results/fast-element_render-createDelete5x.json
    report_results:
      name: Report Results
      needs: [update10th, render]
      runs-on: ubuntu-latest
      steps:
          # Download the results artifact
          - uses: actions/download-artifact@v2
            with:
                name: results
                path: packages/utilities/fast-benchmarks/results

          # Read all the results and post comment
          - name: Report Tachometer Result
            uses: andrewiggins/tachometer-reporter-action@v2
            with:
                name: results
                path: packages/utilities/fast-benchmarks/results/*.json
